# Generated by Django 5.1.7 on 2025-04-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_event_user_alter_event_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="description",
            new_name="course_description",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="title",
            new_name="course_title",
        ),
        migrations.RemoveField(
            model_name="event",
            name="end",
        ),
        migrations.RemoveField(
            model_name="event",
            name="start",
        ),
        migrations.AddField(
            model_name="event",
            name="course_number",
            field=models.CharField(default="CISC-0000-L00", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="days",
            field=models.CharField(default="Mon, Wed", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="instructor",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="times",
            field=models.CharField(default="09:00 AM - 10:00 AM", max_length=100),
            preserve_default=False,
        ),
    ]
