# Generated by Django 5.1.7 on 2025-05-12 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_changelog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="changelog",
            name="event",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="change_logs",
                to="users.event",
            ),
        ),
    ]
